# Phase 5: Enhanced Configuration for MultiFormatHealthcareGenerator
# Unified healthcare data generation and migration platform configuration
# Version: 5.0.0
# Date: 2025-09-10

# ============================================================================
# APPLICATION CONFIGURATION
# ============================================================================

app:
  name: "MultiFormatHealthcareGenerator"
  version: "5.0.0"
  environment: "development"  # development, testing, staging, production
  debug: true
  log_level: "INFO"

# ============================================================================
# CORE GENERATION SETTINGS
# ============================================================================

# Basic data generation parameters
num_records: 100
output_dir: "phase5_generated_data"
seed: 42  # For reproducible generation

# Demographic distributions
age_dist:
  "0-18": 0.15
  "19-40": 0.25
  "41-65": 0.35
  "66-120": 0.25

gender_dist:
  male: 0.48
  female: 0.50
  other: 0.02

race_dist:
  White: 0.60
  Black: 0.18
  Asian: 0.08
  Hispanic: 0.10
  "Native American": 0.02
  Other: 0.02

ethnicity_dist:
  "Not Hispanic or Latino": 0.80
  "Hispanic or Latino": 0.20

# Social determinants of health distributions
smoking_dist:
  Never: 0.60
  Former: 0.25
  Current: 0.15

alcohol_dist:
  Never: 0.35
  Occasional: 0.40
  Regular: 0.20
  Heavy: 0.05

education_dist:
  "High School": 0.25
  "Associate": 0.15
  "Bachelor": 0.30
  "Master": 0.20
  "Doctorate": 0.08
  "None": 0.02

employment_dist:
  Employed: 0.65
  Unemployed: 0.08
  Student: 0.12
  Retired: 0.12
  Disabled: 0.03

housing_dist:
  Stable: 0.85
  Homeless: 0.03
  Temporary: 0.08
  "Assisted Living": 0.04

# ============================================================================
# HEALTHCARE FORMAT CONFIGURATIONS
# ============================================================================

formats:
  fhir_r4:
    enabled: true
    validation_enabled: true
    validation_strictness: "strict"  # strict, moderate, lenient
    profile_validation: true
    terminology_validation: true
    base_url: "https://example.org/fhir"
    batch_size: 100
    include_meta: true
    include_extensions: true
    custom_profiles:
      - "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
      - "http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition"
      - "http://hl7.org/fhir/us/core/StructureDefinition/us-core-medicationstatement"

  fhir_r5:
    enabled: false
    validation_enabled: true
    validation_strictness: "moderate"

  hl7_v2_adt:
    enabled: true
    validation_enabled: true
    validation_strictness: "moderate"
    hl7_version: "2.8"
    encoding: "UTF-8"
    segment_terminator: "\r\n"
    field_separator: "|"
    component_separator: "^"
    repetition_separator: "~"
    escape_character: "\\"
    subcomponent_separator: "&"

  hl7_v2_oru:
    enabled: true
    validation_enabled: true
    validation_strictness: "moderate"
    hl7_version: "2.8"
    include_obx_segments: true
    max_observations_per_message: 50

  hl7_v2_orm:
    enabled: false
    validation_enabled: true
    validation_strictness: "moderate"

  vista_mumps:
    enabled: true
    validation_enabled: true
    validation_strictness: "lenient"
    fileman_date_format: true
    include_global_structure: true
    va_specific_fields: true
    mumps_version: "GT.M"
    global_directory: "^DPT"

  csv:
    enabled: true
    validation_enabled: true
    delimiter: ","
    quote_char: "\""
    escape_char: "\\"
    include_header: true
    flatten_complex_fields: true
    encoding: "utf-8"

  parquet:
    enabled: false
    validation_enabled: true
    compression: "snappy"
    include_metadata: true

  json:
    enabled: true
    validation_enabled: true
    pretty_print: true
    include_schema: false

  xml:
    enabled: false
    validation_enabled: true
    schema_validation: true

# ============================================================================
# MIGRATION SIMULATION SETTINGS
# ============================================================================

migration_settings:
  source_system: "vista"
  target_system: "oracle_health"
  migration_strategy: "staged"  # staged, big_bang, parallel
  simulate_migration: true

  # ETL success rates by stage
  success_rates:
    extract: 0.98
    transform: 0.95
    validate: 0.92
    load: 0.90

  # Failure simulation rates
  failure_simulation:
    network_failure_rate: 0.05
    system_overload_rate: 0.03
    data_corruption_rate: 0.01
    security_violation_rate: 0.001
    terminology_mapping_failure_rate: 0.04

  # Performance settings
  performance:
    concurrent_patients: 10
    batch_size: 50
    retry_attempts: 3
    timeout_seconds: 30
    max_memory_usage_mb: 2048

  # Quality monitoring during migration
  quality_monitoring:
    enabled: true
    real_time_alerts: true
    quality_score_threshold: 0.85
    critical_error_threshold: 0.02
    alert_recipients:
      - "migration-team@example.com"
      - "data-quality@example.com"

# ============================================================================
# DATA QUALITY AND VALIDATION RULES
# ============================================================================

quality_rules:
  # Global quality settings
  overall_quality_threshold: 0.90
  strict_validation_enabled: true
  auto_correction_enabled: false

  # Quality dimension thresholds
  completeness_threshold: 0.95
  accuracy_threshold: 0.90
  consistency_threshold: 0.85
  timeliness_threshold: 0.80
  validity_threshold: 0.95
  uniqueness_threshold: 0.98
  integrity_threshold: 0.90
  hipaa_compliance_threshold: 1.0

  # Clinical data validation rules
  clinical_validation_rules:
    patient_demographics:
      required_fields: ["patient_id", "first_name", "last_name", "gender", "birthdate"]
      optional_fields: ["middle_name", "ssn", "phone", "email"]
      validation_rules: ["age_consistency", "name_format", "contact_validation"]
      criticality_level: "high"

    clinical_conditions:
      required_fields: ["condition", "onset_date", "status"]
      terminology_binding_required: true
      icd10_validation_enabled: true
      snomed_validation_enabled: true
      criticality_level: "critical"

    medications:
      required_fields: ["medication", "dosage", "frequency"]
      rxnorm_validation_enabled: true
      drug_interaction_checking: true
      allergy_checking: true
      criticality_level: "critical"

    allergies:
      required_fields: ["allergen", "reaction", "severity"]
      criticality_level: "critical"

    observations:
      required_fields: ["type", "value", "date"]
      range_validation_enabled: true
      unit_validation_enabled: true
      criticality_level: "medium"

  # Error tolerance levels
  error_tolerance:
    missing_optional_fields: 0.20
    formatting_errors: 0.05
    terminology_mapping_failures: 0.10
    validation_warnings: 0.15

# ============================================================================
# TESTING AND ERROR INJECTION CONFIGURATION
# ============================================================================

testing:
  # Error injection settings
  error_injection_enabled: false  # Enable for testing scenarios
  error_injection_mode: "controlled"  # disabled, controlled, random, scenario_based, stress_test

  error_injection_rates:
    missing_required_fields: 0.02
    invalid_data_formats: 0.03
    terminology_mapping_errors: 0.01
    network_simulation_errors: 0.05
    system_overload_errors: 0.02
    data_corruption_errors: 0.01
    security_violation_errors: 0.001
    validation_failure_errors: 0.04

  # Test scenario configuration
  test_scenarios_enabled: true
  default_test_patient_profiles:
    - "healthy_adult"
    - "chronic_conditions"
    - "pediatric"
    - "geriatric"
    - "emergency_case"
    - "complex_medical_history"

  # Migration testing scenarios
  migration_testing_enabled: true
  migration_test_scenarios:
    vista_to_oracle_health:
      source_system: "vista"
      target_system: "oracle_health"
      patient_count: 25
      success_rates:
        extract: 0.95
        transform: 0.90
        load: 0.88
      failure_scenarios:
        - "network_timeout"
        - "data_corruption"
        - "mapping_error"
        - "validation_failure"

    epic_to_cerner:
      source_system: "epic"
      target_system: "cerner"
      patient_count: 30
      success_rates:
        extract: 0.97
        transform: 0.93
        load: 0.91

# ============================================================================
# SECURITY AND COMPLIANCE CONFIGURATION
# ============================================================================

security:
  # Encryption settings
  encryption_enabled: true
  encryption_key_path: "./keys/healthcare_encryption.key"
  
  # HIPAA compliance
  hipaa_compliance_mode: true
  phi_encryption_required: true
  phi_access_logging: true
  phi_retention_days: 2555  # 7 years

  # Audit logging
  audit_logging_enabled: true
  audit_log_path: "./logs/audit.log"
  audit_log_rotation: "daily"
  audit_log_retention_days: 2555

  # Access control
  access_control_enabled: true
  role_based_access: true
  multi_factor_authentication: false

  # API security
  api_authentication_required: true
  api_rate_limiting_enabled: true
  api_requests_per_minute: 1000

# ============================================================================
# COMPLIANCE CONFIGURATION
# ============================================================================

compliance:
  # Healthcare regulations
  hipaa_enabled: true
  hitech_compliance: true
  meaningful_use_compliance: true
  cures_act_compliance: true
  gdpr_compliance: false  # For international deployments

  # Audit and reporting
  audit_trail_enabled: true
  compliance_reporting_enabled: true
  compliance_report_frequency: "monthly"  # daily, weekly, monthly, quarterly

  # Data retention policies
  data_retention_enabled: true
  patient_data_retention_years: 7
  audit_log_retention_years: 7
  backup_retention_years: 7

# ============================================================================
# MONITORING AND ALERTING CONFIGURATION
# ============================================================================

monitoring:
  enabled: true
  real_time_monitoring: false
  metrics_collection_interval_seconds: 60

  # Alert thresholds
  alert_thresholds:
    error_rate_threshold: 0.05
    quality_score_threshold: 0.80
    performance_degradation_threshold: 0.20
    memory_usage_threshold: 0.85
    disk_usage_threshold: 0.90
    response_time_threshold_ms: 5000

  # Notification settings
  notifications:
    email_enabled: true
    slack_enabled: false
    webhook_enabled: false
    recipients:
      - "healthcare-ops@example.com"
      - "data-quality@example.com"

  # Dashboard settings
  dashboard:
    enabled: true
    refresh_interval_seconds: 30
    real_time_updates: false
    
  # Metrics retention
  metrics_retention_days: 90
  detailed_metrics_retention_days: 30

# ============================================================================
# PERFORMANCE CONFIGURATION
# ============================================================================

performance:
  # Parallel processing
  parallel_processing_enabled: true
  max_concurrent_patients: 10
  thread_pool_size: 4
  batch_size: 100

  # Memory management
  memory_limit_mb: 2048
  memory_cleanup_interval_seconds: 300

  # Caching
  caching_enabled: true
  cache_size_mb: 512
  cache_ttl_seconds: 3600
  terminology_cache_enabled: true
  validation_cache_enabled: true

  # Optimization flags
  lazy_loading_enabled: true
  connection_pooling_enabled: true
  compression_enabled: false
  parallel_validation_enabled: true

  # Resource limits
  max_file_size_mb: 100
  max_generation_time_minutes: 60
  cleanup_temp_files: true
  temp_file_retention_hours: 24

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================

database:
  enabled: false  # Enable if using database storage
  host: "localhost"
  port: 5432
  database: "healthcare_generator"
  username: "healthcare_user"
  password: "${HEALTHCARE_DB_PASSWORD}"  # Use environment variable
  ssl_enabled: true
  connection_pool_size: 10
  timeout_seconds: 30
  schema: "healthcare_data"

# ============================================================================
# TERMINOLOGY SERVICES CONFIGURATION
# ============================================================================

terminology:
  # External terminology services
  external_services_enabled: false
  
  # SNOMED CT
  snomed_ct:
    enabled: true
    version: "US_EDITION_20230901"
    validation_enabled: true
    cache_enabled: true

  # ICD-10-CM
  icd10_cm:
    enabled: true
    version: "2024"
    validation_enabled: true

  # RxNorm
  rxnorm:
    enabled: true
    version: "2024_01_01"
    validation_enabled: true

  # LOINC
  loinc:
    enabled: true
    version: "2.76"
    validation_enabled: true

  # Local terminology cache
  local_cache:
    enabled: true
    cache_size_mb: 256
    update_frequency_days: 30

# ============================================================================
# OUTPUT AND REPORTING CONFIGURATION
# ============================================================================

output:
  # File naming patterns
  file_naming_pattern: "{format}_{timestamp}_{batch_id}"
  timestamp_format: "%Y%m%d_%H%M%S"

  # Output formats and compression
  compression:
    enabled: false
    format: "gzip"  # gzip, zip, bz2

  # Reporting
  reports:
    generation_report_enabled: true
    validation_report_enabled: true
    quality_report_enabled: true
    performance_report_enabled: true
    migration_report_enabled: true
    
    report_format: "json"  # json, yaml, html, pdf
    report_output_dir: "reports"

# ============================================================================
# INTEGRATION CONFIGURATION
# ============================================================================

integrations:
  # External system integrations
  hl7_interface_engine:
    enabled: false
    endpoint: "https://hl7-interface.example.com"
    authentication: "oauth2"

  fhir_server:
    enabled: false
    base_url: "https://fhir.example.com"
    version: "R4"
    authentication: "bearer_token"

  # Messaging and notifications
  message_queue:
    enabled: false
    provider: "rabbitmq"  # rabbitmq, kafka, azure_service_bus
    connection_string: "${MESSAGE_QUEUE_CONNECTION}"

# ============================================================================
# ENVIRONMENT-SPECIFIC OVERRIDES
# ============================================================================

environments:
  development:
    app:
      debug: true
      log_level: "DEBUG"
    num_records: 10
    testing:
      error_injection_enabled: true
    performance:
      max_concurrent_patients: 5

  testing:
    app:
      debug: true
      log_level: "INFO"
    num_records: 25
    testing:
      error_injection_enabled: true
      error_injection_mode: "scenario_based"

  staging:
    app:
      debug: false
      log_level: "WARN"
    num_records: 100
    monitoring:
      real_time_monitoring: true
    security:
      multi_factor_authentication: true

  production:
    app:
      debug: false
      log_level: "ERROR"
    monitoring:
      real_time_monitoring: true
      alert_thresholds:
        error_rate_threshold: 0.01
        quality_score_threshold: 0.95
    security:
      multi_factor_authentication: true
      api_rate_limiting_enabled: true
    performance:
      max_concurrent_patients: 20
      batch_size: 200

# ============================================================================
# FEATURE FLAGS
# ============================================================================

feature_flags:
  advanced_terminology_validation: true
  real_time_quality_monitoring: true
  automated_error_correction: false
  machine_learning_validation: false
  blockchain_audit_trail: false
  natural_language_processing: false
  clinical_decision_support: false

# ============================================================================
# EXPERIMENTAL FEATURES
# ============================================================================

experimental:
  # AI/ML-powered features (future development)
  ai_powered_validation: false
  synthetic_data_enhancement: false
  predictive_quality_scoring: false
  automated_mapping_generation: false
  
  # Advanced interoperability
  fhir_r5_support: false
  hl7_v3_support: false
  dicom_integration: false
  
  # Performance optimizations
  gpu_acceleration: false
  distributed_processing: false
  cloud_native_scaling: false

# ============================================================================
# METADATA
# ============================================================================

metadata:
  configuration_version: "5.0.0"
  created_date: "2025-09-10"
  created_by: "Healthcare Systems Architect"
  last_modified: "2025-09-10"
  description: "Phase 5 unified configuration for MultiFormatHealthcareGenerator platform"
  documentation_url: "https://docs.example.com/healthcare-generator"
  support_contact: "healthcare-support@example.com"