module: asthma
jobs:
  - modules: ["asthma_v2"]
    num_records: 400
    iterations: 8
    kpis:
      - name: childhood_vs_adult_onset
        metric: proportion_split
        groups:
          - attribute: asthma_type
            value: childhood
          - attribute: asthma_type
            value: lifelong
        targets:
          childhood: 0.95
          lifelong: 0.05
        tolerance_abs: 0.05
        sources: [aaaai_asthma_stats]

      - name: annual_attack_rate
        metric: event_rate_per_year
        event: asthma_attack
        target: 0.53
        tolerance_abs: 0.07
        sources: [aaaai_asthma_stats]

      - name: ed_visits_per_100_ptyears
        metric: ed_visits_per_100_ptyears
        event: asthma_ed_visit
        target: 10.0
        tolerance_abs: 2.0
        sources: [cdc_asthma_ed]
