name: Patient Pipeline CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        env:
          PYTHONPATH: .
        run: pytest

      - name: CLI smoke test
        env:
          PYTHONPATH: .
        run: >
          python -m src.core.synthetic_patient_generator
          --num-records 10
          --output-dir output_cli_smoke
          --skip-report
          --skip-hl7
          --skip-fhir
          --skip-vista
